services:
    #angular:
    #    working_dir: /var/www/html
    #    build:
    #       context: ./nginx
    #       dockerfile: Dockerfile
    #    image: nginx:latest
    #    container_name: nginx
    #    ports:
    #        - 4200:4200
    #    links:
    #        - openjdk
    #    depends_on:
    #        - openjdk

    mysql:
        container_name: mysql
        build:
            context: ./mysql
            dockerfile: Dockerfile
        image: mysql:latest
        expose:
            - 3306
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_PASSWORD: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./mysql/data:/var/lib/mysql

    openjdk:
        build: 
            context: ./spring
            dockerfile: Dockerfile
        #expose:
        #    - 9000
        ports:
            - 9001:9001
        environment:
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        links:
            - mysql
        depends_on:
            - mysql
            
    angular:
        container_name: angular
        build: 
            context: ./angular
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        links:
            - openjdk
        depends_on:
            - openjdk
            - mysql
